In [1]:
import arimax as model
import pandas as pd

In [26]:
import numpy as np
a=np.linspace(0,10,11)
b=np.linspace(10,20,11)
c=np.dstack((a,b)).squeeze()
print(np.sqrt(a,b))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]


In [2]:
df=pd.read_csv("Data1997-2022.csv")
df

Unnamed: 0    CPI  Monthly salary  Policy rate  Unemployed
0             0   69.3           20126         3.50         4.0
1             1   69.6           20126         3.50         3.7
2             2   69.7           20126         3.50         3.6
3             3   69.7           20126         3.50         3.4
4             4   69.8           20126         3.50         3.2
..          ...    ...             ...          ...         ...
307         307  123.9           53150         1.75         1.6
308         308  125.6           53150         1.75         1.6
309         309  126.0           53150         2.25         1.6
310         310  125.8           53150         2.50         1.6
311         311  125.9           53150         2.50         1.6

[312 rows x 5 columns]

In [3]:
cpi_diff12 = df['CPI'].diff(12)
exog_data = df[['Monthly salary', 'Policy rate', 'Unemployed']]
cpi_diff12


0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ... 
307    7.6
308    8.1
309    8.8
310    7.7
311    7.0
Name: CPI, Length: 312, dtype: float64

In [10]:
ARX = model.ARMAX(1, 0, 3)
ARX.fit(cpi_diff12[12:], exog_data[12:], 0.0004, 0.4*10**(-12), 10**(-6))

13    -1.4
14    -1.7
15    -1.7
16    -1.5
17    -1.5
      ... 
307   -7.6
308   -8.1
309   -8.8
310   -7.7
311   -7.0
Name: CPI, Length: 299, dtype: float64
[9.98068212e-06 6.22560000e-10 6.68484000e-10]
[0.751468]
13    -0.132162
14    -0.432162
15    -0.206722
16    -0.006722
17    -0.157016
         ...   
307   -1.132930
308   -1.858370
309   -2.182636
310   -0.556608
311   -0.683223
Name: CPI, Length: 299, dtype: float64
[1.08487113e-05 6.81329487e-10 7.16441282e-10]
[0.83668585]
13     0.005909
14    -0.294091
15    -0.043085
16     0.156915
17    -0.010422
         ...   
307   -0.413573
308   -1.164579
309   -1.446236
310    0.239444
311    0.019090
Name: CPI, Length: 299, dtype: float64
[1.07281416e-05 6.78739446e-10 6.97268326e-10]
[0.84895373]
13     0.020478
14    -0.279522
15    -0.024836
16     0.175164
17     0.005373
         ...   
307   -0.323065
308   -1.077751
309   -1.353274
310    0.340994
311    0.107144
Name: CPI, Length: 299, dtype: float64
[1.05069446e-05 6

In [12]:
ARX.predict(cpi_diff12[12:], exog_data[12:])

array([ 1.40575239,  1.40575239,  1.68859182,  1.68859182,  1.5000322 ,
        1.5000322 ,  1.59431201,  1.5000322 ,  1.68859182,  1.59431201,
        1.59431201,  1.69214512,  1.69214512,  1.5035855 ,  1.59786531,
        1.78642493,  1.78642493,  1.69214512,  1.5035855 ,  1.4093057 ,
        1.5035855 ,  1.78642493,  1.97498454,  1.97934776,  2.07362757,
        2.26218718,  1.88506795,  1.88506795,  2.07362757,  2.35646699,
        2.26218718,  2.54502661,  2.54502661,  2.26218718,  2.35646699,
        2.17221501,  2.36077463,  2.64361405,  2.73789386,  2.83217367,
        3.11501309,  2.73789386,  2.0779352 ,  1.9836554 ,  1.70081597,
        1.70081597,  1.32369674,  1.61311871,  1.14171967,  0.67032063,
        0.76460044,  0.57604082,  0.38748121,  0.38748121,  1.23599948,
        1.04743986,  1.14171967,  1.42455909,  1.70739851,  2.08810678,
        3.78514332,  3.78514332,  2.93662505,  2.27666639,  1.61670774,
        1.42814812,  1.23958851,  1.71098755,  1.61670774,  1.33